---
sections:
  - label: Hero Section
    name: hero
    path: content/hero
    templates:
      - hero
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Date Section
    name: date
    path: content/date
    templates:
      - date
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Timeline Section
    name: timeline
    path: content/timeline
    templates:
      - timeline
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Wedding Events
    name: weddingEvents
    path: content/events
    templates:
      - weddingEvents
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
